version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: jitsi:master    # Required. Must be in the same fork network.
    mergeMethod: rebase  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    assignees:              # Optional
      - e4basil
    reviewers:              # Optional
      - e4basil
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - e4basil
  - base: dev
    upstream: master        # Required. Can be a branch in the same forked repo.
    assignees:              # Optional
      - e4basil
    reviewers:              # Optional
      - e4basil
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - e4basil
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
